"""Doing nothing

Revision ID: b0ab4383bb55
Revises: bb5eaa7d6682
Create Date: 2024-06-05 15:10:11.944880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ab4383bb55'
down_revision: Union[str, None] = 'bb5eaa7d6682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'color',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'color',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
